- spec/requests/admin_create_teacher_spec.rb
Spec that check if admin can modify an existing school
> Implement admin_updating_school_spec

- app/controllers/kids_controller.rb
- app/controllers/substitutions_controller.rb
- app/models/kid.rb
- app/models/principal_school_relation.rb
- app/models/schedule.rb
- app/models/substitution.rb
A couple of Code Climate issues popped up from the last PR (indentation issues and duplicate method definition). Might depend on an answer to: https://github.com/panterch/future_kids/commit/d90bbc252ffc2df7f80e15da3f57e50e6f93b15a#commitcomment-15227206
This also makes the spacing at the beginning and end of controller and model Class files a bit more consistent (no empty line at the beginning or end)
> Fix code climate issues

- app/models/ability.rb
- app/models/document.rb
- app/models/journal.rb
- app/models/substitution.rb
- app/models/user.rb
- Some small spacing cleanup
- Uses ActiveRecord `not` conditions http://guides.rubyonrails.org/active_record_querying.html#not-conditions
- One-liner for conditional, with single assignment
> Small cleanups

- app/helpers/application_helper.rb
> Fix Ordnen nach Kontrolldatum

- app/controllers/mentors_controller.rb
- app/helpers/application_helper.rb
- app/models/admin.rb
- app/models/kid.rb
- app/models/mentor.rb
- app/views/mentors/index.html.haml
- db/migrate/20161222121149_remove_primary_kids_admin_id_from_user.rb
- db/structure.sql
- spec/models/admin_spec.rb
- spec/models/kid_spec.rb
- spec/models/mentor_spec.rb
- spec/requests/filter_mentors_on_coaches_spec.rb
Fixes mentor filtering on coaches when admins are assigned to many mentors (through kids).
> Mentors filtered by coaches

- app/controllers/substitutions_controller.rb
- app/views/substitutions/_form.html.haml
- spec/requests/substitutions_workflow_spec.rb
Mentors and kids are coupled in substitutions.
> Coupled kids mentors

- app/assets/stylesheets/application.css.scss
Align checkboxes by setting padding-left to 0px.
> override bootstrap setting for checkboxes

- app/assets/javascripts/global.js.erb
Set 2h max duration in journal.
> Duration of mentoring in journal

- .travis.yml
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css.scss
- spec/requests/documents_spec.rb
- spec/requests/show_kid_mentors_schedules_spec.rb
- spec/requests/support/request_helpers.rb
- spec/spec_helper.rb
> Selenium chrome

- app/controllers/application_controller.rb
- app/controllers/kids_controller.rb
- app/models/ability.rb
- app/views/kids/_form.html.haml
- spec/controllers/kids_controller_spec.rb
> let pricipals create kids

- app/models/mentor.rb
- app/views/mentors/index.xlsx.axlsx
- config/locales/future_kids.de.yml
- spec/models/mentor_spec.rb
> report hours logged in mentor's spreadsheet

- app/controllers/reviews_controller.rb
- app/models/ability.rb
- app/views/kids/_show.html.haml
To be fixed: flash notice has wrong text "Schüler geslöscht"
> WIP: admins can destroy reviews: fixes #178

- app/controllers/application_controller.rb
- app/controllers/kid_mentor_relations_controller.rb
- app/controllers/kids_controller.rb
Hey there, I did this pull request to solve the issue #179
I hope it helps!
> Fix potencial SQL Injection problems

- app/controllers/kids_controller.rb
- app/helpers/application_helper.rb
- app/models/review.rb
- app/views/documents/index.html.haml
- app/views/kids/index.html.haml
- app/views/mentors/_form.html.haml
- app/views/mentors/_show.html.haml
- app/views/substitutions/index.html.haml
- spec/controllers/reviews_controller_spec.rb
- principals can filter kids
- record coaching on kid 
- changed texts / fixed typos
> Minor changes

- README.md
ln 6 11/2 looks like 11 divided by 2 rather than one and a half. 1 1/2 looks better though 1.5 would be best
ln 14 rephrase for better wording
> fixed some readme grammar

- app/assets/javascripts/global.js.erb
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/mixins.css.scss
- app/views/layouts/_actions.html.haml
- app/views/layouts/_navigation_items.html.haml
- app/views/layouts/application.html.haml
- config/initializers/show_for.rb
- spec/requests/substitutions_workflow_spec.rb
- spec/spec_helper.rb
Added basic mobile interface
I had to update Capybara config to take only visible elements,
because mobile actions and menu are hidden.
> Basic mobile interface

- Gemfile
- Gemfile.lock
- lib/tasks/schedule.rake
Add whenever task definitions as rake tasks so that they can be executed with herokus scheduler dyno.
> Find a way to execute cron jobs

- Gemfile
- Gemfile.lock
- INSTALL.md
- app/models/concerns/has_coordinates.rb
- app/models/kid.rb
- app/models/user.rb
- config/initializers/geocoder.rb
- db/migrate/20200526121729_add_coords_to_kids.rb
- db/migrate/20200526130657_add_coords_to_users.rb
- spec/models/kid_spec.rb
- spec/models/mentor_spec.rb
- added geocoder gem to facilitate geocoding functionality
- implemented to user+kid model
- stores latitude/longitude if address is supplied
> Geocoding support

- app/controllers/kids_controller.rb
- app/controllers/mentors_controller.rb
- app/controllers/schools_controller.rb
- app/controllers/teachers_controller.rb
- app/models/application_record.rb
- app/models/school.rb
- app/views/schools/_form.html.haml
- app/views/schools/_show.html.haml
- config/locales/future_kids.de.yml
- db/migrate/20200604123200_add_school_kind_to_schools.rb
- spec/models/school_spec.rb
School kind enum field is added to school
Values: High school, Gymnasium, Secondary school, Primary school
Dropdown is added to edit/create form and on show detail page
> feat: added school kind enum to school

- app/helpers/application_helper.rb
- app/views/kids/index.html.haml
- app/views/mentors/index.html.haml
- app/views/teachers/index.html.haml
- config/locales/future_kids.de.yml
add school filtering option to mentors
limit school filter options based on kid / teacher / mentor's allowed school kinds
> feat: filter mentors by school

- app/helpers/application_helper.rb
- app/views/mentors/_form.html.haml
- app/views/mentors/index.html.haml
- app/views/teachers/_form.html.haml
- app/views/teachers/index.html.haml
#251 – add filters for user state on teachers & mentors page
> feat: add user status filters

- app/controllers/self_registrations_controller.rb
- app/views/mentors/_form.html.haml
- spec/models/ability_mentor_spec.rb
- spec/models/ability_teacher_spec.rb
Feedback mentioned in https://github.com/panterch/future_kids/pull/279 fixes
> fix: self-registration PR feedback fixes

- Gemfile
- Gemfile.lock
- app/controllers/self_registrations_controller.rb
- app/controllers/sites_controller.rb
- app/models/site.rb
- app/views/self_registrations/_new_mentor.haml
- app/views/self_registrations/_new_teacher.haml
- app/views/self_registrations/terms_of_use.html.haml
- app/views/sites/_form.html.haml
- config/locales/future_kids.de.yml
- config/routes.rb
- db/migrate/20210517155237_add_terms_of_use_content_to_site.rb
- spec/controllers/self_registrations_controller_spec.rb
- spec/models/site_spec.rb
- spec/requests/self_registrations.rb
> feat: terms of use

- app/controllers/self_registrations_controller.rb
- app/controllers/sites_controller.rb
- app/views/devise/sessions/new.html.erb
- app/views/sites/_form.html.haml
- config/locales/future_kids.de.yml
- db/migrate/20210518155536_add_public_signups_active_to_site.rb
- spec/controllers/self_registrations_controller_spec.rb
- spec/requests/self_registrations.rb
> feat: disable self registrations

- app/controllers/available_kids_controller.rb
- app/controllers/mentor_matchings_controller.rb
- app/mailers/notifications.rb
- app/models/ability.rb
- app/models/kid.rb
- app/models/mentor.rb
- app/models/mentor_matching.rb
- app/models/teacher.rb
- app/views/available_kids/index.html.haml
- app/views/layouts/_navigation_items.html.haml
- app/views/mentor_matchings/_form.html.haml
- app/views/mentor_matchings/_show.html.haml
- app/views/mentor_matchings/index.html.haml
- app/views/mentor_matchings/show.html.haml
- app/views/mentors/_details.html.haml
- app/views/mentors/_show.html.haml
- app/views/notifications/mentor_matching_created.text.erb
- app/views/notifications/mentor_matching_declined.text.erb
- app/views/notifications/mentor_matching_reserved.text.erb
- config/locales/future_kids.de.yml
- config/routes.rb
- db/migrate/20210518095427_create_mentor_matchings.rb
- spec/factories.rb
- spec/models/ability_admin_spec.rb
- spec/models/ability_mentor_spec.rb
- spec/models/ability_teacher_spec.rb
- spec/requests/available_kids_spec.rb
- spec/requests/mentor_matchings_spec.rb
https://github.com/panterch/future_kids/issues/259 https://github.com/panterch/future_kids/issues/260 https://github.com/panterch/future_kids/issues/261
> Add mentor matchings

- app/helpers/application_helper.rb
- app/models/ability.rb
- app/models/kid.rb
- app/models/mentor_matching.rb
- app/views/available_kids/index.html.haml
- app/views/mentor_matchings/index.html.haml
- config/locales/future_kids.de.yml
- spec/requests/available_kids_spec.rb
- spec/requests/mentor_matchings_spec.rb
https://github.com/panterch/future_kids/issues/303
> Add available kids mentor matching actions

- app/controllers/self_registrations_controller.rb
- app/models/mentor.rb
- app/models/teacher.rb
- app/views/self_registrations/_new_mentor.haml
- app/views/self_registrations/_new_teacher.haml
- app/views/self_registrations/success.html.haml
- config/locales/future_kids.de.yml
- spec/controllers/self_registrations_controller_spec.rb
- spec/factories.rb
- spec/requests/self_registrations.rb
https://github.com/panterch/future_kids/issues/301
> Registration fields adaptions

- app/helpers/application_helper.rb
- app/views/kid_mentor_relations/index.html.haml
- app/views/mentor_matchings/index.html.haml
- app/views/substitutions/index.html.haml
Action buttons are conssitent buttons (not links) around the app. Also for deleting it's red, and for submitting is green.
> Action buttons

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
After user is loged in, it redirects to different page based on step where a user is: 
- mentor has no kids -> go to available kids page or 
- teacher have some pending mentor invitations -> go to mentor matching page
> After login redirects

- app/views/available_kids/index.html.haml
- app/views/kids/index.html.haml
- app/views/mentor_matchings/index.html.haml
- config/locales/future_kids.de.yml
> feat: page descriptions

- app/views/mentors/_form.html.haml
- app/views/teachers/_form.html.haml
Covers: https://github.com/panterch/future_kids/issues/297
> feat: hide passowrd fileds
